name: build
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  build_natives:
    permissions:
      contents: write
    name: Build natives libraries
    runs-on: ubuntu-20.04
    steps:
      - name: Make space
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
          java-package: jdk
          cache: 'maven'
      - name: Source versions from VERSION file
        run: cat VERSION >> $GITHUB_ENV

      - name: Display version
        run: echo $sqliteMCVersion $version $artifactVersion

      - name: Build binaries, test, and package
        env:
          OCI_EXE: docker
        run: make all
      - name: Package DLL binaries
        run: zip -r ./sqlite-natives-$artifactVersion.zip ./src/main/resources/org/sqlite/native
      - uses: actions/upload-artifact@v2
        with:
          name: SQLiteMC DLL Binaries
          path: |
            ./sqlite-natives-${{ env.artifactVersion }}.zip
            ./target/*.jar

      - name: Prepare GPG sign
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          openssl aes-256-cbc -K ${{ secrets.ENCRYPTED_KEY }} -iv ${{ secrets.ENCRYPTED_IV }} -in ./scripts/private.key.enc -out /tmp/private.key -d
          gpg --version
          gpg --batch --import /tmp/private.key
          rm /tmp/private.key
      - name: Deploy version
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        if: startsWith(github.ref, 'refs/tags/')
        run: make deploy
      - name: Deploy Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "SQLite-jdbc-${{ env.artifactVersion }}"
          generate_release_notes: true
          files: |
            ./sqlite-natives-${{ env.artifactVersion }}.zip
            ./target/sqlite-jdbc-${{ env.artifactVersion }}.jar
            ./target/sqlite-jdbc-${{ env.artifactVersion }}-javadoc.jar
            ./target/sqlite-jdbc-${{ env.artifactVersion }}-sources.jar
            ./target/sqlite-jdbc-${{ env.artifactVersion }}.jar.asc
            ./target/sqlite-jdbc-${{ env.artifactVersion }}-javadoc.jar.asc
            ./target/sqlite-jdbc-${{ env.artifactVersion }}-sources.jar.asc

